steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      cat <<EOF > /root/.kube/config
      $$KUBECFG
      EOF
    secretEnv: ['KUBECFG']
    volumes:
    - name: 'kube'
      path: /root/.kube
  - name: alpine/helm:3.11.3
    env:
    - KUBECONFIG=/root/.kube/config
    script: |
      #!/usr/bin/env sh
      helm upgrade \
        --install \
        --values=$_VALUES_PATH \
        --set=image.fullTagOverride=$_IMAGE_TAG \
        --set=ingress.hosts[0].host=$_HOST \
        --set=ingress.tls[0].hosts[0]=$_HOST \
        --set=migrations.image.fullTagOverride=${_REGION}-docker.pkg.dev/$PROJECT_ID/outofschool/oos-migrations:${_IMAGE_TAG##*:}
        --wait \
        $_SERVICE_NAME \
        ./k8s/webapp
    volumes:
    - name: 'kube'
      path: /root/.kube
availableSecrets:
  secretManager:
  - versionName: $_KUBE_CONFIG
    env: 'KUBECFG'
options:
  automapSubstitutions: true
  pool:
    name: $_POOL
