apiVersion: v2
name: elastic
description: A Helm chart for Elastic & optional Kibana & Logging Agent Vector

type: application

version: 20230902+v4

appVersion: "8.5.1"

dependencies:
  - name: elasticsearch
    version: 8.5.1
    repository: https://helm.elastic.co
  - name: kibana
    version: 8.5.1
    condition: kibana.enabled
    repository: https://helm.elastic.co
  - name: vector
    version: 0.20.1
    condition: vector.enabled
    repository: https://helm.vector.dev
  - name: metricbeat
    version: 8.5.1
    condition: metricbeat.enabled
    repository: https://helm.elastic.co

