# TODO: Think how to make it simpler so it can be moved to Elastic PostStart
elasticConfigJob:
  enabled: true

elasticsearch:
  enabled: true
  clusterName: "elasticsearch"
  nodeGroup: "master"

kibana:
  enabled: true

metricbeat:
  enabled: true

vector:
  enabled: true
