# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global: {}

nameOverride: ""
fullnameOverride: ""

commonLabels:
  tier: frontend
  service: frontend

image:
  fullTagOverride: ""
  pullPolicy: IfNotPresent

deploy:
  containerPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/issuer: "letsencrypt"
    cert-manager.io/duration: 2160h0m0s
    cert-manager.io/renew-before: 168h0m0s
  hosts:
    - host: "replace_me"
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: "replace_me_staging"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
  - secretName: frontend-tls
    hosts:
    - replace_me
  - secretName: frontend-staging-tls
    hosts:
    - replace_me_staging
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPU: 60
  targetMemory: 80

readinessProbe:
  enabled: false
  port: http
  path: "/"
  initialDelaySeconds: 20
  timeoutSeconds: 1
  periodSeconds: 20
  failureThreshold: 3
  successThreshold: 1

serviceAccount:
  imagePullSecrets:
  - name: outofschool-gcp-pull-secrets
