architecture: standalone
auth:
  enabled: true
  sentinel: true
  existingSecret: redis-auth
  existingSecretPasswordKey: password
  usePasswordFiles: false
master:
  persistence:
    enabled: true
    storageClass: standard
    size: 1Gi
# commonConfiguration: |-
#   # Enable AOF https://redis.io/topics/persistence#append-only-file
#   appendonly yes
#   # Disable RDB persistence, AOF persistence already enabled.
#   save ""
resources:
  requests:
    cpu: 20m
    memory: 10Mi
  limits:
    cpu: 150m
    memory: 192Mi
