apiVersion: v2
name: webapp
description: A Helm chart for OutOfSchool application for Kubernetes

type: application

version: 1.0.6

appVersion: ""

dependencies:
  - name: library
    version: ~0.1.0
    repository: "file://../library"
  - name: job
    alias: migrations
    condition: migrations.enabled
    version: ~0.1.0
    repository: "file://../job"
