# Replaced by MariaDb CRDs
# Do not delete in case we need it.
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE USER IF NOT EXISTS '<METRICS_USER>'@'%';
    ALTER USER IF EXISTS '<METRICS_USER>'@'%' IDENTIFIED BY '<METRICS_PASSWORD>';
    GRANT SELECT, REPLICATION CLIENT, SHOW DATABASES, SUPER, PROCESS, EXECUTE ON *.* TO '<METRICS_USER>'@'%';
    GRANT CREATE, INSERT ON mysql.* TO '<METRICS_USER>'@'%';
    FLUSH PRIVILEGES;
