eck-elasticsearch:
  enabled: true
  version: 8.5.1
  fullnameOverride: "elasticsearch"
  annotations:
    eck.k8s.elastic.co/license: "basic"
  nodeSets:
  - name: "elastic"
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch analysis-icu
            bin/elasticsearch-plugin install --batch analysis-ukrainian
            bin/elasticsearch-plugin install --batch mapper-murmur3
        containers:
        - name: elasticsearch
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1768Mi"
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: "standard"
        resources:
          requests:
            storage: 15G
eck-kibana:
  enabled: true
  fullnameOverride: "kibana"
  annotations:
    eck.k8s.elastic.co/license: basic
  spec:
    count: 1
    elasticsearchRef:
      name: "elasticsearch"
    podTemplate:
        spec:
          containers:
          - name: kibana
            env:
              - name: NODE_OPTIONS
                value: "--max-old-space-size=2048"
            resources:
              requests:
                cpu: "200m"
                memory: "512Mi"
              limits:
                cpu: "500m"
                memory: "1256Mi"




