controller:
  service:
    enabled: true
    externalTrafficPolicy: Local
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
  config:
    proxy-body-size: 100m
    use-forwarded-headers: "true"
    log-format-escape-json: "true"
    log-format-upstream: '{"timestamp": "$time_iso8601", "request_id": "$req_id",
      "user": {"agent": "$http_user_agent", "name": "$remote_user"},
      "network": {"remote_ip": "$proxy_protocol_addr", "x_forwarded_for": "$proxy_add_x_forwarded_for"},
      "http": {"version": "$server_protocol", "request": {"method": "$request_method", "referrer": "$http_referer", "size_bytes": "$request_length"},"response":{"size_bytes": "$bytes_sent","status": "$status","duration_sec": "$request_time"}, "upstream":{"size_bytes": "$upstream_response_length", "status": "$upstream_status", "duration_sec": "$upstream_response_time", "address": "$upstream_addr", "name": "$proxy_upstream_name", "alternative_name": "$proxy_alternative_upstream_name"}},
      "url": {"vhost": "$host", "path": "$uri", "query": "$args", "original":"$request_uri"}}'
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
defaultBackend:
  enabled: true
  autoscaling:
    # TODO: wait till the bug fix will be updated as a chart of HPA
    enabled: false
    minReplicas: 1
    maxReplicas: 2
