# Replaced by MariaDb CRDs
# Do not delete in case we need it.

global: {}

jobKind: Job

backoffLimit: 3
activeDeadlineSeconds: 500
ttlSecondsAfterFinished: 86400
restartPolicy: "Never"

image:
  registry: "container-registry.oracle.com"
  repository: "mysql"
  name: "community-server"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "8.4.2"
  fullTagOverride: ""

command:
  - bash
  - '-c'
  - |
    until mysql -h mysql -u$rootUser -p$rootPassword mysql -e "quit" &>/dev/null; do echo "Trying to connect to database..."; sleep 10; done
    sed -e "s|<METRICS_USER>|${METRICS_USER}|g" \
        -e "s|<METRICS_PASSWORD>|${METRICS_PASSWORD}|g" /tmp/initdb.sql | mysql -u$rootUser -p$rootPassword -h mysql mysql

configuration:
  extraEnvironment: {}

  extraEnvVarsCM: ""

  extraEnvVarsSecret: "mysql-cluster-secret"

  secrets:
  - type: env
    name: mysql-user-agent
    keys:
    - key: user
      envKey: METRICS_USER
    - key: password
      envKey: METRICS_PASSWORD

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podSecurity:
  enabled: false
  context:
    fsGroup: 2000
    ## e.g:
    ## sysctls:
    ##   - name: net.core.somaxconn
    ##     value: "10000"
    ##
    sysctls: []

containerSecurity:
  enabled: false
  context:
    runAsUser: 1000
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

extraVolumeMounts:
  - name: mysql-initdb
    mountPath: /tmp

extraVolumes:
  - name: mysql-initdb
    configMap:
      name: mysql-initdb-config
