enabled: true
ingress:
  enabled: true
  hostname: ""
  pathType: ImplementationSpecific
  annotations:
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    cert-manager.io/issuer: "letsencrypt"
    cert-manager.io/duration: 2160h0m0s
    cert-manager.io/renew-before: 168h0m0s
  tls: true
  ingressClassName: nginx
db:
  enableSsl: false
  allowArbitraryServer: false
  host: "mysql-instances"
resources:
  requests:
    cpu: 50m
    memory: 50Mi
  limits:
    cpu: 375m
    memory: 384Mi
