extraVolumes:
  - name: gcp-ksa
    projected:
      sources:
      - serviceAccountToken:
          audience: ${GCP_PROJECT_ID}.svc.id.goog
          path: token
      - configMap:
          items:
          - key: config
            path: ${GSP_KSA_FILE}
          name: ${GSP_KSA_CONFIGMAP}
          optional: false

extraVolumesMounts:
  - name: gcp-ksa
    mountPath: ${GCP_KSA_TOKEN_PATH}
    readOnly: true

extraEnv:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value:  ${GCP_KSA_TOKEN_PATH}/${GSP_KSA_FILE}
  - name: GAIA_TOKEN_EXCHANGE_ENDPOINT
    value: https://sts.googleapis.com/v1/token

